#!/bin/bash
set -e
if [ -n "$1" ]; then
    filename=$(basename -- "$1")
    filename_without_ext=${filename%.*}
    pandoc $1 --pdf-engine=xelatex -o $filename_without_ext.pdf
else
    echo "No parameters was given"
fi

