#!/bin/bash

# MOVES LAST FILE IN DOWNLOADS DIRECTORY TO $1 
if [ $# -eq 0 ]
  then
    echo "No arguments given"
    exit 1
fi

detox ~/Downloads
last_file=$(ls -t ~/Downloads | head -n1)
if [ "$1" == "peek" ]; then
    echo $last_file;
else
    echo $last_file;
    mv ~/Downloads/$last_file $1;
fi
