#!/usr/bin/env bash
# Script for detaching zathura from terminal when opening pdf
if [ $# -eq 0 ]; then
    file=$(find . -name "*\.pdf" | head -n1)
    if [ file != "" ]; then
        zathura $file &!
        exit 0
    fi
    echo 'No pdf found'
    exit 1
fi

if [ $# -eq 1 ] && [ -f "$1" ]; then
    zathura $1 &! 
    exit 0
fi

if [ $# -eq 2 ] && [ -f "$2" ]; then
    okular $2 &! 
    exit 0
fi

echo "File doesnt exist"
exit 1
