#!/usr/bin/env bash
# Script for detaching zathura from terminal when opening pdf
if [[ $# -eq 0 ]]; then
    echo 'Takes one(1) pdf as argument'
    exit 0
fi

if [ $# -eq 1 ]; then
    zathura $1 &! 
fi

if [ $# -eq 2 ]; then
    okular $2 &! 
fi
